- app/controllers/catalog_controller.rb
- app/controllers/concerns/galtersufia/collections_controller_behavior.rb
- app/models/collection.rb
- app/presenters/galter_collection_presenter.rb
- app/views/collections/_show_actions.html.erb
- app/views/collections/_show_descriptions.html.erb
- app/views/collections/_show_document_list.html.erb
- app/views/collections/_show_relations.html.erb
- app/views/collections/_sort_and_per_page.html.erb
- app/views/collections/show.html.erb
- app/views/my/_index_partials/_list_collections.html.erb
- app/views/sufia/forms/galter_collection_edit_forms/edit_fields/_multi_page.html.erb
- config/initializers/sufia.rb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/collections_controller_spec.rb
- spec/features/collections_spec.rb
- spec/features/muti_page_collections_spec.rb
- spec/models/collection_spec.rb
- spec/rails_helper.rb
Might as well PR it as I forgot to mention in a commit that this also fixes #86
> Multi page collection

- app/controllers/users_controller.rb
- app/views/_user_util_links.html.erb
- app/views/roles/index.html.erb
- app/views/users/new.html.erb
- config/initializers/resque_admin.rb
- config/initializers/stats_admin.rb
- config/routes.rb
- spec/features/admin_spec.rb
- spec/features/user_spec.rb
Add an admin area of a sort with links to adminy things.
> Allow admins to create users, fixes #468

- lib/batch/arey.rb
- lib/batch/batch_load_template.rb
- lib/batch/library_notes.rb
- lib/batch/library_notes_extact_dates.sh
As requested by @sharpattack, here are the batch scripts for loading things into DH. The one for Arey might need to be updated a bit still.
> Scripts to load Library Notes and Arey book

- lib/batch/fsm_audio_interviews.rb
Fixes #542 
FYI @sharpattack no review required. This is a one-time script that I already used.
> Script for batch loading the Special collection audio files

- lib/batch/institutional_students_collection.rb
Moves "Masters in Public Health CE Papers" collection to "Students' Collection" collection before converting to institutional collection.
> script to create institutional students collection, closes #559

- Capfile
- Gemfile
- Gemfile.lock
- app/controllers/concerns/galtersufia/collections_controller_behavior.rb
- app/controllers/custom_authorities_controller.rb
- app/helpers/galter_collections_helper.rb
- app/views/collections/index.html.erb
- config/deploy.rb
- config/initializers/rack_profiler.rb
- config/initializers/user_stat_importer_initializer.rb
- config/schedule.rb
- spec/controllers/collections_controller_spec.rb
- spec/models/user_stat_importer_spec.rb
- spec/views/collections/index.html.erb_spec.rb
* make the collection index faster as explained in the commit message
* fix security bugs for some of the the gems -- I've tested the functionality that relies on the updated gems in staging.
> Performance optimization and security update

- config/deploy.rb
- config/schedule.rb
Tested on staging, works ok. Also tested the stats gathering task and it works fine.
> Silence cron and switch email forwording to galter-is

- app/models/generic_file.rb
- app/views/records/show_fields/_doi.html.erb
- lib/batch/wos_api.rb
- lib/batch/wos_open_load.rb
- spec/features/generic_file_spec.rb
- spec/models/generic_file_spec.rb
> Link DOIs to preferred resolver (fixes #582)

- app/assets/stylesheets/application.css.erb
- app/controllers/application_controller.rb
- app/controllers/concerns/galtersufia/contact_form_controller_behavior.rb
- app/views/contact_form/new.html.erb
- spec/controllers/contact_form_controller_spec.rb
- spec/features/contact_form_spec.rb
> Add bot-thwarting measures to contact form

- app/views/homepage/_featured_fields.html.erb
- app/views/homepage/_recent_document.html.erb
- spec/features/home_page_spec.rb
> Remove filename from featured and recent on homepage

- app/views/generic_files/_show_actions.html.erb
- app/views/generic_files/show.html.erb
- app/views/layouts/_head_tag_content.html.erb
- spec/support/sufia_factories.rb
- spec/views/generic_files/_show_actions.html.erb_spec.rb
Pending altmetric approval for our production and staging sites.
closes #574.
> Add altmetric donut

- Gemfile.lock
- app/models/concerns/ezid_generator.rb
- db/datacite_xsd/include/datacite-contributorType-v4.xsd
- db/datacite_xsd/include/datacite-dateType-v4.1.xsd
- db/datacite_xsd/include/datacite-descriptionType-v4.xsd
- db/datacite_xsd/include/datacite-funderIdentifierType-v4.xsd
- db/datacite_xsd/include/datacite-nameType-v4.1.xsd
- db/datacite_xsd/include/datacite-relatedIdentifierType-v4.xsd
- db/datacite_xsd/include/datacite-relationType-v4.1.xsd
- db/datacite_xsd/include/datacite-resourceType-v4.1.xsd
- db/datacite_xsd/include/datacite-titleType-v4.xsd
- db/datacite_xsd/metadata.xsd
- spec/features/generic_file_spec.rb
- spec/models/generic_file_spec.rb
This code is already in production :(
I had to wait for them to move the prefix to finalize my tests.
> Switch EZID to Datacite for DOI processing

- lib/batch/institutional_oncofertility.rb
- basic institutional collection. closes #624
> Create Institutional Collection Dialogues in Oncofertility

- app/controllers/concerns/galtersufia/collections_controller_behavior.rb
- app/controllers/concerns/galtersufia/files_controller_behavior.rb
- app/models/collection.rb
- app/models/generic_file.rb
- spec/features/collections_spec.rb
- spec/features/generic_file_spec.rb
> Collection and files JSON representations

- Gemfile.lock
- app/controllers/concerns/galtersufia/collections_controller_behavior.rb
- app/controllers/concerns/galtersufia/files_controller_behavior.rb
- app/models/collection.rb
- app/models/concerns/ezid_generator.rb
- app/models/generic_file.rb
- db/datacite_xsd/include/datacite-contributorType-v4.xsd
- db/datacite_xsd/include/datacite-dateType-v4.1.xsd
- db/datacite_xsd/include/datacite-descriptionType-v4.xsd
- db/datacite_xsd/include/datacite-funderIdentifierType-v4.xsd
- db/datacite_xsd/include/datacite-nameType-v4.1.xsd
- db/datacite_xsd/include/datacite-relatedIdentifierType-v4.xsd
- db/datacite_xsd/include/datacite-relationType-v4.1.xsd
- db/datacite_xsd/include/datacite-resourceType-v4.1.xsd
- db/datacite_xsd/include/datacite-titleType-v4.xsd
- db/datacite_xsd/metadata.xsd
- lib/batch/institutional_oncofertility.rb
- spec/features/collections_spec.rb
- spec/features/generic_file_spec.rb
- spec/models/generic_file_spec.rb
- Switch from EZID to Datacite(already on the production server)
- JSON formatted Collections and GenericFiles
> 1.14.0-datacite-and-json-format

- lib/batch/institutional_nucats_grants.rb
Need to change permissions after executing.
> create and institutionalize NUCATS Grants Repository. closes #636

- lib/batch/institutionalize_t_series.rb
> Move 'T Series' and 'Grants Resources' to 'NUCATS Grants Repository'

- lib/batch/institutionalize_12th_GH.rb
Placed under parent collection "Galter Health Sciences Library"
collection. closes #645
> Institutionalize 12th General Hospital

- lib/batch/batch_metadata_updates_634.rb
- spec/models/collection_spec.rb
> original_publisher, publisher, and based_near Batch updates

- lib/batch/subject.csv.rb
- Script was just living on the server, and should be a part of
the code base so we do not lose it. We will need to come up
with a different solution for these requests though, see #635
> closes #644 - add metadata extraction script

- app/presenters/galter_collection_presenter.rb
- app/presenters/galter_generic_file_presenter.rb
- lib/batch/batch_metadata_updates_655.rb
- transfer the values to (Digital) Publisher field. closes #655
> Disable Original Publisher field

- app/presenters/galter_collection_presenter.rb
- app/presenters/galter_generic_file_presenter.rb
- lib/batch/batch_metadata_updates_634.rb
- lib/batch/batch_metadata_updates_655.rb
- lib/batch/institutional_nucats_grants.rb
- lib/batch/institutionalize_12th_GH.rb
- lib/batch/institutionalize_t_series.rb
- spec/models/collection_spec.rb
Batch update for Publisher field script needs to be run. The rest were manually uploaded to the server and already run.
> Release 1.15.0-disable_Original_Publisher-update_and_institutionalize_scripts

- lib/batch/institutionalize_12th_GH.rb
- lib/batch/institutionalize_mason_and_connor_sub_collections.rb
> [#669] Institutionalize sub collections for Mason and Conner

- lib/batch/institutionalize_psychiatry_and_behavorial_sciences.rb
Add sub collections
- Department Events
- Conferences
- Commencement
- Grand Rounds
- Scholars Day
- Newsletters
Closes #670
> [#670] Institutionalize Department of Psychiatry and Behavioral Sciences

- lib/batch/institutional_nucats_cecd.rb
- lib/batch/institutional_nucats_grants_repo_child_collections.rb
- lib/batch/institutionalize_mason_selected_docs.rb
Institutionalize "Mason Selected Documents"
- also includes already institutionalized work for NUCATS Grants Repository
> Release 1.17.1-Mason_Selected_Documents

- lib/batch/institutionalize_davis_papers.rb
Institutionalize work for "Nathan Smith Davis papers" collection, under 'Special Collections'.
> Release 1.17.2-Nathan_Smith_Davis_papers

- lib/batch/create_blank_nucats_subcollections.rb
- lib/batch/institutionalize_f_series.rb
Institutionalize "F-Series" and create 10 templates with 3 child
templates for NUCATS Grants Repository. closes #690, closes #691
> [#690, #691] F-Series and templates

- lib/batch/institutionalize_davis_papers.rb
Under "NUCATS Grants Repository" collection - 
- Institutionalize work for "F-Series" collection
- Create 10 Institutional Collection templates, with 3 child collections
> Release 1.17.3-F_Series-and-Template_Collections

- lib/batch/institutional_nucats_cecd.rb
- lib/batch/institutional_nucats_grants_repo_child_collections.rb
- lib/batch/institutionalize_12th_GH.rb
- lib/batch/institutionalize_davis_papers.rb
- lib/batch/institutionalize_mason_and_connor_sub_collections.rb
- lib/batch/institutionalize_mason_selected_docs.rb
- lib/batch/institutionalize_psychiatry_and_behavorial_sciences.rb
- Switch to Exponential Backoff throttle rules. 
- Script to get google analytics view and download stats for a Collection.
> Release 1.18.0-Exponential_Throttle-and-Google_Stats_for_Collection

- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
- config/local_env_public.rb
- config/locales/devise.en.yml
- spec/features/shibboleth_auth_spec.rb
Switch to new production and staging shibboleth signout url, update
logout flash message to reflect new behavior, set shibboleth metadata
through capistrano. closes #716
> [#716] Update websso sign out url

- .gitignore
- README.md
Add notes to README to help with installing and running the application.
closes #717
> [#717] Update README With Setup Instructions

- lib/batch/institutionalize_19-20_BCC.rb
Move Ashley Knudson's file, "Finding Your Way..." to collection
"2019-2020" created by user ccb638(Biostatistics), then institutionalize
under "Biostatistics Collaboration Center Lecture Series" collection.
closes #723
> [#723] Institutionalize work for BCC Lecture Series

- config/local_env_public.rb
See issue for alternate logout url. closes #729
> [#729] Fix logout url typo

- app/assets/stylesheets/application.css.erb
- app/views/layouts/homepage.html.erb
Requested directly from the dean, through Ann Crago. Add resources for
coronavirus to top of the page. closes #732
> [#732] Add Emergency Ribbon

- app/assets/stylesheets/application.css.erb
- app/views/_masthead.html.erb
- app/views/layouts/homepage.html.erb
Add link to Northwestern University's coronavirus page. closes #735
> [#735] Update Emergency Ribbon Message

- app/assets/stylesheets/application.css.erb
- app/views/_masthead.html.erb
- app/views/layouts/homepage.html.erb
Add link to Northwestern University's coronavirus page.
> Release 1.19.2-Add_NU_Coronavirus_to_Ribbon

- app/views/_masthead.html.erb
Updates to banner as requested by Ann Crago. Closes [#735]
> [#735] 3/18/20 Update to Emergency Ribbon

- lib/batch/institutionalize_bids_jam.rb
Institutionalize Chicago Biomedical Data Science Jam, add collection
member "Chicago Biomedical Data Science Jam 2016".
Add collection member "Biomedica Data Science Day 2016" to "Biomedical
Data Science Day".
closes #706
> [#706] Institutional Chicago Biomedical Date Science Jam

- lib/batch/institutionalize_bids_jam.rb
Institutionalize work for Center for Data Science and Informatics Collection
- Chicago Biomedical Data Science Jam
- Chicago Biomedical Data Science Jam 2016
- Biomedical Data Science Day
- Biomedica Data Science Day 2016
> Release 1.20.01-Institutional_BDSD_and_BIDSJam

- lib/batch/institutional_communication_bridge.rb
Create new institutional collection "Communication Bridge", closes #767
> [#767] Insitutional Communication Bridge

- lib/batch/institutional_communication_bridge.rb
Create new institutional collection "Communication Bridge"
> Release 1.20.2-Institutional_Communication_Bridge

- lib/scripts/users_list.rb
- lib/tasks/users_list.rake
- spec/lib/scripts/users_list_spec.rb
Export user info to csv file using rake task. closes #770
> [#770] Export User Info

- lib/scripts/collections_tags_and_mesh.rb
- lib/tasks/collections_tags_and_mesh_list.rake
- spec/lib/scripts/collection_members_view_and_download_stats_spec.rb
- spec/lib/scripts/collections_tags_and_mesh_spec.rb
- spec/lib/scripts/users_list_spec.rb
Export collections tags and mesh info to csv file using rake.
closes #771
> [#771] Export Collections Tags and Mesh

- lib/scripts/collection_items_list.rb
- lib/scripts/get_collection_items_list.rb
- spec/lib/scripts/collection_items_list_spec.rb
Export a list of items in a collection. closes #775
> [#775] CSV of Collection Items

- lib/batch/institutional_gv_black_papers.rb
> [#776] Institutional GV Black Papers

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
proxy_depositor is mapped to created_by. closes #785
> [#785] Export Provenance Field

- app/models/concerns/galtersufia/generic_file/known_organizations.rb
- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
> [#791] Export Metadata Subfield Creators

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
This branch has been rebased off of here: #812 so it would be best to hold off on reviewing this until that is merged. Once it is merged this PR will show only the title fields. I just want to make sure I get everything up and ready to go now so I don't get distracted with something else and forget before the long weekend.
> 792 export metadata subfields title and additional titles

- lib/batch/institutional_pepper_center_818.rb
Create new institutional collection Northwestern Pepper Center.
Sub/child collections to be added using create_blank_subcollections
script. closes #818
> [#818] Institutional Northwestern Pepper Center

- lib/scripts/users_list.rb
- spec/lib/scripts/users_list_spec.rb
Export script updated to include total deposits and last deposit date.
closes #770
> [#770] Export User Info W Deposits

- app/controllers/custom_authorities_controller.rb
- app/models/concerns/galtersufia/generic_file/header_lookup.rb
- app/models/invenio_rdm_record_converter.rb
- config/routes.rb
- spec/cassettes/CustomAuthoritiesController/_lcnaf_names/invalid_query/no_results_returned/returns_empty_array.yml
- spec/cassettes/CustomAuthoritiesController/_lcnaf_names/valid_query/lower_case_query/returns_values_from_LOC.yml
- spec/cassettes/CustomAuthoritiesController/_lcnaf_names/valid_query/upper_case_query/returns_values_from_LOC.yml
- spec/cassettes/CustomAuthoritiesController/_lcnaf_names/valid_query/with_one_result/returns_one_value_from_LOC.yml
- spec/controllers/custom_authorities_controller_spec.rb
- spec/models/invenio_rdm_record_converter_spec.rb
> [#795] Export Metadata Subfield Subjects

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
> [#804] Export Metadata Subfield Locations

- app/models/concerns/galtersufia/generic_file/header_lookup.rb
- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
> [#795] Export Meta Subfield Subjects Redux

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
> [#797] Export Metadata Subfield Dates

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Another simple and to the point PR. This has been rebase off of 795 Subfield Subjects Redux so review that first.
> [#794] Export Metadata Subfields Publisher And Publication Date

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Very small and straightforward PR.
> [#798] Metadata Subfield Languages

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Add sizes subfield to metadata function. Only page counts are included
at this time. closes #800
> [#800] Metadata Subfield Sizes

- export_dh_users_with_groups.rb
Add script for exporting a CSV of file owner data. closes #753
> [#753] Create List Of Netid, Email, Fullname From Owners Of Records

- app/models/concerns/galtersufia/generic_file/license_data.txt
- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
> [#803] Export Metadata Subfield Rights

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
- spec/support/sufia_factories.rb
> [#802] Export Metadata Subfield Versions

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
> [#784] Export Invenio Access Field

- app/models/concerns/galtersufia/generic_file/license_data.txt
- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Update InvenioRdmRecordConverter#rights to export expected json for all
rights reserved license.
> [#803] Export Metadata Subfield Rights All Rights Reserved

- app/models/header_lookup.rb
- spec/models/header_lookup_spec.rb
Encode mesh and lcsh searches to support special characters. closes #861
> [#861] Special Characteres Break Header Queries

- config/deploy.rb
- lib/batch/add_tag_nucats_867.rb
- lib/batch/add_tags_for_collection_members.rb
- spec/lib/batch/add_tags_for_collection_members_spec.rb
For NUCATS Grants Repository collection, add tag to all non collection
items. closes #867
> [#867] Add NUCATS tag for Collection

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Add information for "files" field to export JSON. closes #25
> [#25] Set Files Enabled To True

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Add subfield to locations JSON, move array into this subfield.
closes #30
> [#30] Update Locations Field

- README.md
- lib/tasks/debug.rake
Add rake tasks to help with debugging. Log file id and title while
running export. closes #864
> [#864] Nil Value Breaking Build Creator Contributor JSON

- lib/batch/institutionalize_NUCATS_Series_DEMR.rb
Institutiotnalize collection. closes #875
> [#875] NUCATS Series On Developing and Enhancing Mentoring Relationships

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Refactor publication date formatting to use strftime instead of with
string interpolation. Zero pad month and day. closes #29
> [#29] Fix Publication Date Format

- app/models/concerns/galtersufia/generic_file/invenio_resource_type_mappings.rb
- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Update resource types field to latest version of InvenioRDM. closes #26
> [#26] Update Resource Types Field

- app/models/concerns/galtersufia/generic_file/license_data.txt
- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Update licenses/rights to new format. closes #856
> [#856] Revisit Licenses/Rights

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Re-opened from earlier PR.
No changes since that PR, other than this has the latest changes.
> 799 subfield identifiers

- lib/scripts/create_keywords_yaml.rb
Script to generate YAML file of tags formatted for InvenioRDM.
closes #888
> [#888] Generate Tags YAML File

- app/models/header_lookup.rb
- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Update metadata subfield subjects for June 2021 InvenioRDM release.
closes #857
> [#857] Revisit Metadata Subfield Subjects

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Use subject_geographic to populate locations metadata. closes #891
> [#891] Revisit Locations

- Gemfile
- Gemfile.lock
- config/deploy.rb
Upgrade passenger to 5.3.4, closes #900
> [#900] Upgrade to Passenger 5.3.4

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
> [#908] Export Funding Should Be An Array

- lib/scripts/users_list.rb
- spec/lib/scripts/users_list_spec.rb
Include user's title and address to UsersList. This is to help get a
better idea of their affiliation. closes #915
> [#915] Add title and address to UsersList

- app/models/concerns/galtersufia/generic_file/license_data.txt
- spec/models/invenio_rdm_record_converter_spec.rb
The IDs should be downcased. closes #922
> [#922] Downcase License IDs

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Change creators and contributors identifiers subfield to an array.
closes #926
> [#926] Export Creators Contributors Identifiers Should Be Array

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
> [#924] Add ID to Dates

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Map acknowledgements field from digitalhub to prism. closes #943
> [#943] Acknowledgements Mapping

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
> [#948] Add Abstract To Additional Descriptions

- Gemfile
- Gemfile.lock
- app/models/concerns/doi_generator.rb
- app/models/concerns/ezid_generator.rb
- app/models/datacite_rest.rb
- app/models/generic_file.rb
- spec/cassettes/GenericFile/_check_doi_presence/all_required_metadata_present/doi_already_present/does_not_originate_from_Galter/does_nothing.yml
- spec/cassettes/GenericFile/_check_doi_presence/all_required_metadata_present/doi_already_present/multiple_dois_one_originating_from_Galter/updates_the_metadata_remotely_but_not_the_ids_locally.yml
- spec/cassettes/GenericFile/_check_doi_presence/all_required_metadata_present/doi_already_present/originates_from_Galter/updates_the_metadata_remotely_but_not_the_ids_locally.yml
- spec/cassettes/GenericFile/_check_doi_presence/all_required_metadata_present/doi_already_present/originates_from_Galter_and_visibility_set_to_open/updates_the_metadata_remotely_but_not_the_ids_locally.yml
- spec/cassettes/GenericFile/_check_doi_presence/all_required_metadata_present/doi_already_present/originates_from_Galter_and_visibility_set_to_restricted/updates_the_metadata_remotely_but_not_the_ids_locally.yml
- spec/cassettes/GenericFile/_check_doi_presence/all_required_metadata_present/generic_file_of_type_Page/with_no_page_number_metadata/creates_the_doi.yml
- spec/cassettes/GenericFile/_check_doi_presence/all_required_metadata_present/no_date_uploaded/sets_doi.yml
- spec/cassettes/GenericFile/_check_doi_presence/all_required_metadata_present/sets_doi.yml
- spec/cassettes/GenericFile/_check_doi_presence/all_required_metadata_present/when_visibility_set_to_public/sets_doi.yml
- spec/models/generic_file_spec.rb
- spec/support/vcr_setup.rb
Switch to Datacite REST API from EZID API.
> 930 datacite rest api

- app/models/concerns/doi_generator.rb
- spec/models/generic_file_spec.rb
Post merge review suggested changes for #970. closes #973
> [#973] PR 970 Review

- app/models/header_lookup.rb
- app/models/invenio_rdm_record_converter.rb
- build_memoized_lcnaf.rb
- memoized_lcnaf.txt
- spec/fixtures/mock_lcnaf.yml
- spec/models/header_lookup_spec.rb
- spec/models/invenio_rdm_record_converter_spec.rb
- trim_lcnaf.rb
Add script to trim lcnaf.skos.ndjson file, extend existing header lookup
to include lcnaf lookup within trimmed file. closes #954
> [#954] Support LCNAF Subject Name Ids

- app/models/generic_file.rb
- app/models/invenio_rdm_record_converter.rb
- spec/models/generic_file_spec.rb
Add GenericFile#unexportable? and use it within InvenioRdmRecordConverter. closes #125, #965
> [#125][#965] Unexportable Records

- app/models/header_lookup.rb
- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
> [#979] Export Record To Final Communities Information

- app/models/invenio_rdm_record_converter.rb
- app/models/role_store.rb
- lib/scripts/repo_export_in_batches.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Add Role Store to export, expand users in permission group, and create
file with info of all Roles and members. closes #902
> [#902] Export Role Group

- lib/batch/institutional_covid_19_992.rb
Create new institutional collection 'COVID 19 Community' closes #992
> [#992] COVID19 Community Collection

- app/models/invenio_rdm_record_converter.rb
Strip whitespace from terms before lookup. closes #1036
> [#1036] 1036-update_lcsh_mesh_terms_lookup

- lib/batch/subject.csv.rb
Add new columns 'isPartOf' and 'id'. closes #1011
> [#1011] subjects.csv Changes

- app/models/invenio_rdm_record_converter.rb
When a creator or contributor's orcid identifier is *not* present it
should be omitted. This was accidentally left out due to merge conflicts
with the previous release.
> [#] Null Identifiers For Creator/Contributor

- lib/batch/subject.csv.rb
For subjects.csv export. closes #1062
> [#1062] Fix Collection IDs

- README.md
- app/models/invenio_rdm_record_converter.rb
- lib/batch/subject.csv.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Small fixes for problems with the export most important of which is a fixing a breaking bug with identifying Pediatric Neurology Briefs
Going to double check this since there were some frustrating merge conflicts, but the specs are green on my local instance and from what I can tell all the commits have been applied.
> Release 1.29.1-mid_august_2022_export_updates

- app/models/invenio_rdm_record_converter.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Export digitalhub page_number and bibliographic_citation as additional descriptions. closes #1022
> 1022 Export Custom Fields Number In Sequence And Original Citation

- app/models/invenio_rdm_record_converter.rb
The latest release will resync master and production so there are a lot of commits going in. This removes some code that should not be left in, but has no effect.
After merging this we can open the release PR which will have the many commits needed to resync.
> [#] Resyncing Commits Between Master And Prod

- app/models/invenio_rdm_record_converter.rb
Updates logic for exporting publisher so that Pediatric Neurology Briefs will use "Pediatric Neurology Briefs Publishers" instead of "Digital Hub" as the publisher. closes #1027
> [#1027] Switch Publishing Order In Some Cases

- app/models/invenio_rdm_record_converter.rb
Specify page count for records with erroneous pdf page counts. closes #1088
> [#1088] PDF Page Counts For Some Records Is Off

- app/models/invenio_rdm_record_converter.rb
Small bug that was found after the original ticket had been closed. re-closes #1110
> [#1110] September 2022 Release Export Bug Fixes Addon

- app/models/generic_file.rb
- spec/models/invenio_rdm_record_converter_spec.rb
Ignore records with either "- combined" or "- Combined" in the title. closes #1113
> [#1113] Ignore Records With Combined In Title

- app/models/generic_file.rb
- app/models/invenio_rdm_record_converter.rb
- lib/scripts/repo_export_in_batches.rb
- spec/models/invenio_rdm_record_converter_spec.rb
* Account for two files with bad page counts
* General bug fixes for updates from previous release
* Ignore records with "- Combined" in the title
> Release 1.30.2 - End of September 2022 Export Updates

- app/models/invenio_rdm_record_converter.rb
> [#1124] Strip Leading and Ending Whitespace From DOI Identifier

- lib/scripts/export_list_of_all_collections_with_id_title_visibility.rb
Simple script to list out collections and specified attributes. closes #1139
> [#1139] Export List of All Collections With ID, Title, and Visibility

- app/models/invenio_rdm_record_converter.rb
- dh_collections_prism_collection_community.json
Update dh collection to prism collection and community json to include mappings from previously unmapped collections. closes #1127
> [#1127] Records Failing to Map to Prism Community

- app/models/invenio_rdm_record_converter.rb
- app/models/role_store.rb
- memoized_lcnaf.json
- memoized_lcsh.json
Handle cases where permissions are in role store. closes #1123
> [#1123] Titlecase Josh Elder Email Whereever It Is

- app/models/role_store.rb
- spec/models/role_store_spec.rb
There was a variable that was misnamed within RoleStore#build_store_data that has been corrected and confirmed working with a small test.
> 1.30.6 Hotfix For December 2022 Export Updates

- lib/batch/subject.csv.rb
To the metadata export, subjects.csv. closes #1168
> [#1168] Add File Format and Page Count

- app/views/_user_util_links.html.erb
- app/views/batch_edits/_check_all.html.erb
- app/views/collections/_show_document_list_menu.html.erb
- app/views/collections/edit.html.erb
- app/views/collections/show.html.erb
- app/views/contact_form/new.html.erb
- app/views/generic_files/show.html.erb
- app/views/my/_action_menu.html.erb
- app/views/my/_collection_action_menu.html.erb
- app/views/my/_sort_and_per_page.html.erb
- app/views/shared/_attributes.html.erb
Calling User#sunset_editor? on nil users raises errors. Add safe navigation operator to calls
> Hotfix - No Method Error When Current User Nil
