galterlibrary/digital-repository

app/views/roles/edit.html.erb, spec/features/admin_spec.rb
not sure why, but it was previously passing the username instead.
=> pass user id to remove user. fixes #553

public/robots.txt
Using twitter card validator, https://cards-dev.twitter.com/validator, our robots.txt disallow crawling to the path of the image.
=> allow twitterbot to crawl dh. fixes #573

Gemfile, Gemfile.lock, config/application.rb, config/deploy.rb, config/initializers/rack_attack.rb, config/newrelic.yml, spec/requests/rack_attack_spec.rb
Use rack-attack to throttle requests. Based on recent events, we
track subnets and set limits based on:
- if a user is signed in or not
- if the request path is to /catalog(?|/)
NU networks are whitelisted, and known abusive subnets are handled in
the apache configs. closes #672
=> [#672] Handle Abusive Requests

Gemfile, Gemfile.lock, config/application.rb, config/deploy.rb, config/initializers/rack_attack.rb, config/newrelic.yml, lib/batch/institutionalize_12th_GH.rb, lib/batch/institutionalize_mason_and_connor_sub_collections.rb, lib/batch/institutionalize_psychiatry_and_behavorial_sciences.rb, spec/requests/rack_attack_spec.rb
**Track requests by the subnet of its ip**
Throttle limits are set based on:
- user signed in? 
- request is to '/catalog?'
For non-signed in users, limits to all paths are strict, while limits to '/catalog?' paths are extreme. For signed in users, all limits are at least 10x looser. 
---
**Institutionalize Collections work**
Add new sub-collections for:
- Mason: 7 new sub-collections
- Conner: 5 new sub-collections
New Institutional collection:
- The Department of Psychiatry and Behavioral Sciences
=> 1.17.0-throttle_catalog-institutionalize_work

lib/batch/institutional_nucats_cecd.rb, lib/batch/institutional_nucats_grants_repo_child_collections.rb
New Parent Institutional Collection
- NUCATS Center for Education and Career Development
- Move NUCATS Grants Repository into this collection
New child collections for NUCATS Grants Repository
- Federal Non-NIH
- U-series
- R-series
- Grants Resources
- Pink Sheets
- Biosketches
closes #678
=> [#678] NUCATS Grants Repository Changes

config/initializers/rack_attack.rb, spec/requests/rack_attack_spec.rb
- Exponentially throttle unauthenticated user requests to /catalog(?|/)
path.
- Custom throttled response to inform users to log in.
- Do not throttle authenticated/logged in users.
=> [#696] Exponentially throttle requests to /catalog, and more

app/views/_masthead.html.erb, spec/features/home_page_spec.rb
In #masthead of the header. closes #713.
=> [#713] Update Logo url from NM to FSM

Gemfile, Gemfile.lock
- loofah
- rack
- rubyzip. see 1.3.0 release notes for security setting fix
- nokogiri
- haml dependency
- mini_magick
- rake
- puma
- websocket-extensions
closes #701
=> Round of Dependency Updates

lib/batch/add_publisher_for_collection_members.rb, lib/batch/add_publisher_to_12th_general_hospital_745.rb, spec/lib/batch/add_publisher_for_collection_members_spec.rb
Add default DigitalHub publisher to items in the 12th General Hospital
collection without a publisher. Create method that can be reused for
other collections. closes #745
=> [#745] Add Publisher to 12th General Hospital

Gemfile.lock, app/models/invenio_rdm_collection_converter.rb, app/models/invenio_rdm_record_converter.rb, db/schema.rb, lib/tasks/repo_export.rake
Create skeleton subclass from Sufia export converter to handle
InvenioRDM specific export. Create a rake task to encapsulate parameters
specific to this export. closes #788
=> [#788] Create Sufia Export Subclass InvenioRdmConverter

Gemfile, Gemfile.lock
In development and testing, eager_load is set to false which causes
errors when trying to run resque-1.27.4. Staging and Production has
eager_load set to true. closes #809
=> [#809] Revert Resque in Development

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
This should be merged after 791 and 792 since it rebases off of those. Very small and simple PR.
=> [#801] Export Metadata Subfield Formats

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
=> [#793] Export Metadata Subfields Description And Additional Descriptions

lib/batch/fix_series_iv_827.rb
For each subcollection's GenericFile, move it 'back' one collection
level to Series IV. The subcollection to be deleted after confirming
move. closes #827
=> [#827] Series IV Collection

lib/batch/fix_series_iv_827.rb
Items in the subcollection were Pages, and not GenericFile, and had
combined_file relation to the subcollection. Check if item is Page, and
remove the combined_file relation. closes #844
=> [#844] Rework Series IV Script

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
Update structure for Invenio export "languages" field to match release
for June 2021. closes #27
=> [#27] Update Exported Languages

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
The depositor for a GenericFile is used as the 'owner'. The netid is
stored as 'username' for User. Look them up and extract the netid and
email and add to Extras field. closes #895
=> [#895] Add Owner Email and Netid to Extras

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
Export the permissions for each GenericFile. Added to the "extras"
section, for each permission type(read/edit), store the user's
netid(username). closes #896
=> 896 record permissions

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
Update title, description, and rights (license) fields to use
localization hash. closes #906
=> [#906] Restructure Exported Title Description Fields With Localization

app/models/header_lookup.rb, app/models/invenio_rdm_record_converter.rb
Remove calls to mesh and lcsh lookup apis. When a subject lookup can not
find a term locally, output information for looking up manually.
closes #939
=> [#939] Update Header Lookup To Only Check Local Sources

app/models/collection_store.rb
Output collections that are self containing, or is jointly contained
with another collection. Keep the export going. closes #977
=> [#977] Debug collection_store

communities.json
Honestly this is for pure synchrony: the final communities.json file is likely in galter-ir-importer or outside version control altogether.
=> replace '&' by 'and' in communities id/title

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
Do not allow subjects that are not mapped to vocabularies to appear
twice in the export json. closes #1002
=> [#1002] Duplicate Subject

app/models/invenio_rdm_record_converter.rb, lib/scripts/repo_export_in_batches.rb, spec/models/invenio_rdm_record_converter_spec.rb
The script that invokes the converters for the export was checking that
the instance of a converter existed, but not if the JSON produced from
the metadata was empty or not. closes #1012
=> [#1012] 2022-04-8 Empty Files

app/models/header_lookup.rb, subjects_mesh.yml
Local mesh lookups are failing because git lfs is not installed on
staging or production which causes subjects_mesh.yml to not get
decompressed. Instead of using git lfs copy the subject files to each
server and add constants in local_env.rb to point to the files.
closes #1016
=> [#1016] Local Mesh Lookups Raising Errors

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
Add wrapper function #format_dates to keep empty strings from adding
erroenous json to the export.  closes #953
=> [#953] Missing Dates

lib/scripts/find_unmappable_subject_terms.rb
Script to check GenericFile mesh and lcsh subjects against memoized
subjects to find which terms are not mapping to the vocabularies.
closes #1029
=> [#1029] Identifiy Un-Mappable Terms

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
Join GenericFile#description with double new lines - "\n\n" rather than
taking the first value as the primary description and mapping the rest
to additional descriptions. closes #1025
=> [#1025] Combine Split Description

app/models/header_lookup.rb, app/models/invenio_rdm_record_converter.rb, build_memoized_lcnaf.rb, memoized_lcnaf.txt, memoized_lcsh.txt, memoized_mesh.txt, spec/models/header_lookup_spec.rb, spec/models/invenio_rdm_record_converter_spec.rb
Update export to search lcnaf file for geographic subject names. Update
build_memoized_lcnaf.rb to search lcnaf for subject_name and
subject_geographic fields to build cache. Update lcnaf searchable file
to use jsonl instead of csv. closes #1032
=> [#1032] Geographic Subject Terms

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
Export the GenericFile filed based_near values with the prefix
"presentation_location: " as additional descriptions with the type
"other". closes #1033
=> [#1033] Export Location

README.md, app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
The previous iteration expected all PNB collections to follow the same
format, but some PNB collections do not have an issue number which was
causing errors when attempting to convert to an integer. closes #1037
=> [#1037] Fix Missing Pediatric Briefs Community Assignment Redux

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
Export DH identifiers that are part of a recognized scheme
Previously this was blocked while we waited for answers about files related to the 12th General Hospital, but it turns out that the files are not needed.
=> [#1023] Original Identifiers

app/models/concerns/galtersufia/generic_file/known_organizations.rb, app/models/invenio_rdm_record_converter.rb
Previous refactors introduced a bug where a User object is expected, but
nil values were being referenced. Also in previous refactors creatibutor
json was updated to have identifiers under the key "person_or_org". Ruby
hashes can be constructed with strings as key, but must be looked up
with symbols. closes #1068
=> [#1068] 2022-08-17 Repo Export Bug Fixes

app/models/invenio_rdm_record_converter.rb
Refactor to use format_additional function which handles empty values
closes #1079
`format_additional` checks each value to see if it's blank. If page_number is blank or nil then `[@generic_file.page_number.to_s.force_encoding("UTF-8")]` will return `[""]` which will then be skipped in `format_additonal`
=> [#1079] Remove Empty Number In Sequence

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
Change map call in InvenioRdmRecordConverter#funding to mutate the array
that it is operating on resolving an issue where blank funding data was
being exported. closes #1056
Very simple fix here. Added a spec too
=> [#1056] Empty Funding Information For Record

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
Update InvenioRdmRecordConverter#owner_info to take the username as an argument and to check specifically for Josh's email that is then replaced with the proper casing. closes #97
=> [#97] Change Josh's Email In Metadata

app/models/generic_file.rb
This is based on what we discussed at today's meeting. The golden egg as @fenekku called it 😄 
Previously the wrong id was being used, but the logic surrounding what should be exported from within is not changed.
=> [#] Update GV Black Collection To Correct ID

app/models/invenio_rdm_record_converter.rb, spec/models/invenio_rdm_record_converter_spec.rb
When the page count for a file is blank return an empty array to be compatible with the Prism importer. closes #1122
=> [#1122] Return Blank Array For Sizes As Last Alternative

app/models/invenio_rdm_record_converter.rb
Previously Josh's email address was only being titlecased for the owner_info export field, but it also needs to titlecased in the other places where it appears. closes #1123
=> [#1123] Titlecase Josh's Email Wherever It Is

app/models/generic_file.rb, lib/scripts/repo_export_in_batches.rb
Export script will now remove the previous export directory automatically if it exists. This will prevent any situations where files that had previously been exported, but are no longer being exported are still included by accident.
=> [#1100] GV Black Item Issues

app/models/role_store.rb, spec/models/role_store_spec.rb
Frustrating that I overlooked this. Oh well. We can do a small release after this is merged and go from there. 
Replace "r" with "role" in RoleStore#build_rolestore_data. Add spec to ensure that this method is not going to error out again.
=> [#] Hotfix - Variable Misnamed For RoleStore

memoized_lcnaf.json
Update memoized LCNAF terms to correctly map University of Chicago. cloes #451
=> [#451] Univeristy of Chicago Subject Not Mapping Correctly
